// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAbQKa-mpsITwxfW7sm4BBmqvcD3oODMQ',
    appId: '1:722012835675:web:d4f0e2e57dcdea5175d47e',
    messagingSenderId: '722012835675',
    projectId: 'internship-task-78001',
    authDomain: 'internship-task-78001.firebaseapp.com',
    storageBucket: 'internship-task-78001.firebasestorage.app',
    measurementId: 'G-NMZ9G697TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjXdG_XsffLLL1ZGJoj4Dm-6L7n6cO_RQ',
    appId: '1:722012835675:android:b83e530be8fc7dc875d47e',
    messagingSenderId: '722012835675',
    projectId: 'internship-task-78001',
    storageBucket: 'internship-task-78001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcqXqMLnzlR9_aMYJO3GpHlHRoe4YfuKs',
    appId: '1:722012835675:ios:ba2686a78f59411f75d47e',
    messagingSenderId: '722012835675',
    projectId: 'internship-task-78001',
    storageBucket: 'internship-task-78001.firebasestorage.app',
    iosBundleId: 'com.example.internshipTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcqXqMLnzlR9_aMYJO3GpHlHRoe4YfuKs',
    appId: '1:722012835675:ios:ba2686a78f59411f75d47e',
    messagingSenderId: '722012835675',
    projectId: 'internship-task-78001',
    storageBucket: 'internship-task-78001.firebasestorage.app',
    iosBundleId: 'com.example.internshipTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAbQKa-mpsITwxfW7sm4BBmqvcD3oODMQ',
    appId: '1:722012835675:web:21b5bbecd6ac05a775d47e',
    messagingSenderId: '722012835675',
    projectId: 'internship-task-78001',
    authDomain: 'internship-task-78001.firebaseapp.com',
    storageBucket: 'internship-task-78001.firebasestorage.app',
    measurementId: 'G-B60XJZM5V8',
  );
}
